eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    metadataMap:
      user.name: ${security.user.name:}
      user.password: ${security.user.password:}
  client:
    serviceUrl:
      defaultZone: http://${security.user.name:}:${security.user.password:}@registry.earth.com:12000/registry/