spring:
  cloud:
    consul:
      host: registry.earth.com
      port: 8500
      discovery:
        tags: user.name=${security.user.name:},user.password=${security.user.password:}
    discovery:
      healthCheckPath: ${management.contextPath:}/health
      healthCheckInterval: 15s
      instanceId: ${spring.application.name}:${vcap.application.instanceId:${spring.application.instanceId:${random.value}}}
   