
spring:
  redis:
    host: localhost
    port: 6379
    
server: 
  port: 18100


earth:
  loginUrl: /login.html
  antMatchers: 
    - /
    - /
    - /login
  guideName: guide
  guidePassword: guide
  guideRole: USER 
