server:
  port: 18000
  

spring:
  application:
    name: cloud-config
  profiles:
    active: native
    
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config-repo,classpath:/config-repo/{application}
        git:
          uri: https://gitee.com/justlive1/earth.git
          searchPaths: config-repo
          
encrypt:
  keyStore:
    location: classpath:/configServer.jks
    password: letmein
    alias: config.earth.com
    secret: justlive1  
    
management:
  security:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:18888/eureka/