server:
  port: 12000

logging:
  file: registry.log
  
earth:
  registry:
    path: /registry

spring:
  application:
    name: registry
  profiles:
    active: security

eureka:
  server:
    enableSelfPreservation: true
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}${earth.registry.path:/eureka}/
      
---
spring:
  profiles: security
  boot:
    auth: 
      enabled: true
      
security:
  user:
    name: mgmt
    password: mgmt-security