eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${register.port:${server.port}}
  client:
    enable: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://registry.earth.com:12000/registry