eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${register.port:${server.port}}
  client:
    enable: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://mgmt:mgmt-security@registry.earth.com:12000/registry
      
      
endpoints:
  auditevents:
    enabled: true
  mappings: 
    enabled: true
  metrics:
    enabled: true
  trace:
    enabled: true
  heapdump:
    enabled: true
  env: 
    enabled: true