eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${register.port:${server.port}}
  client:
    enable: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://mgmt:mgmt-security@registry.earth.com:12000/registry
      
spring:
  cloud:
    consul:
      host: registry.earth.com
      port: 8500
      discovery:
        tags: user.name=${security.user.name},user.password=${security.user.password}
    discovery:
      instanceId: ${spring.application.name}:${vcap.application.instanceId:${spring.application.instanceId:${random.value}}}
      
      
endpoints:
  auditevents:
    enabled: true
  mappings: 
    enabled: true
  metrics:
    enabled: true
  trace:
    enabled: true
  heapdump:
    enabled: true
  env: 
    enabled: true