spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: 127.0.0.1:3306/dev?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource

mybatis:
  typeAliasesPackage: git.oschina.net.justlive1.breeze.rain.api.domian
  configuration:
    mapUnderscoreToCamelCase: true
