spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dbtest
    username: sa
    password:
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:db/schema.sql
    data: classpath:db/init-data.sql

mybatis:
  typeAliasesPackage: git.oschina.net.justlive1.breeze.rain.api.domian
  configuration:
    mapUnderscoreToCamelCase: true
