spring:
  application:
    name: rain-web

  aop:
    auto: true
    proxy-target-class: true
  freemarker:
    charset: UTF-8
    check-template-location: true
    enabled: true
    prefix:
    suffix:
    request-context-attribute: request
    template-loader-path: classpath:/templates/
    view-names: '*.ftl'

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


  redis:
    host: localhost
    port: 6379


cloud:
  loginUrl: /login
  successUrl: /main
  antMatchers:
    - /webjars/**
    - /logout
    - /login
  guideName: guide
  guidePassword: guide
  guideRole: USER
