  
lighting:
  core:
    tmpPath: /tmp/snow/
    logPath: /tmp/logs/snow/
    
    
    remotes: {
        GITHUB: {
            type: GITHUB,
            refPrefix: refs/heads,
            filePath: archive,
            fileSuffix: .zip,
            agent: GitHub-Hookshot,
            event: push
          }
      }

    resources: {
        ZIP: {
            type: ZIP,
            handles: []
          }
      }

    builds: {
        NODE: {
            type: NODE,
            envPath: /usr/local/bin/,
            cmds: [npm install, npm run build],
            handles: []
          }
      }
      
    deploys: {
        STATIC: {
            type: STATIC,
            handles: []
          }
      }