  
lighting:
  core:
    tmpPath: /tmp/snow/
    logPath: /tmp/logs/snow/
    defaultSteps: 
      - resourceStep
      - buildStep
      - deployStep
      
    remotes: {
        GITHUB: {
            type: GITHUB,
            refPrefix: refs/heads,
            filePath: archive,
            fileSuffix: .zip,
            agent: GitHub-Hookshot,
            event: push
          }
      }

    resources: {
        ZIP: {
            type: ZIP,
            handles: [downloadStep, unzipStep]
          }
      }

    builds: {
        NODE: {
            type: NODE,
            envPath: /usr/local/bin/,
            cmds: [npm install, npm run build],
            handles: []
          }
      }
      
    deploys: {
        STATIC: {
            type: STATIC,
            handles: []
          }
      }
      
      
  project:
    projects: {
        website-master: {
            id: website-master,
            sourceType: ZIP,
            buildType: NODE,
            deployType: STATIC,
            deployPath: /tmp/snow/
          }
      }